[project]
name = "comfyui-ollama-nodes"
description = "ComfyUI custom nodes for working with [a/Ollama](https://github.com/ollama/ollama).\nNOTE:Assumes that an Ollama server is running at http://127.0.0.1:11434 and accessible by the ComfyUI backend."
version = "1.0.2"
license = { text = "GNU General Public License v3.0" }
dependencies = ["ollama", "huggingface_hub"]

[project.urls]
Repository = "https://github.com/slyt/comfyui-ollama-nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "slyt"
DisplayName = "comfyui-ollama-nodes"
Icon = "https://github.com/slyt/comfyui-ollama-nodes/blob/main/comfyui-ollama-nodes-logo.png?raw=true"
